# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/chrivers/bifrost:master-2025-04-29"
  aarch64: "ghcr.io/chrivers/bifrost:master-2025-04-29"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bifrost"
  org.opencontainers.image.description: "Bifrost enables you to emulate a Philips Hue Bridge to control lights, groups and scenes from Zigbee2Mqtt."
  org.opencontainers.image.source: "https://github.com/chrivers/bifrost"
  org.opencontainers.image.licenses: "GNU GPLv3"
args:
  TEMPIO_VERSION: "2021.09.0"
